name: Mobile UI tests (self-hosted with Appium)

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: self-hosted
    timeout-minutes: 90

    defaults:
      run:
        shell: cmd   

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Run tests (tag @bild_news_login)
        env:
          DEVICE_UDID: ${{ env.DEVICE_UDID }}
          ANDROID_VERSION: ${{ env.ANDROID_VERSION }}
          DEVICE_MODEL: ${{ env.DEVICE_MODEL }}
        run: mvn -B clean test -Dcucumber.filter.tags="@bild_news_login"

      - name: Generate Allure report (static site)
        if: always()
        run: mvn -B io.qameta.allure:allure-maven:report || exit /b 0

      - name: Upload single-file Allure HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-single-file
          path: allure-report.html
          if-no-files-found: warn
          retention-days: 14

      - name: Upload Allure results (raw)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results
          if-no-files-found: warn
          retention-days: 14

      - name: Upload Allure HTML report (static site)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-site
          path: target/site/allure-maven-plugin
          if-no-files-found: warn
          retention-days: 14
